<a href="https://colab.research.google.com/github/annagradziel12/NumPy/blob/master/numpy_%C4%87wiczenia_IRIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## IRIS DATASET

In [ ]:
import numpy as np

In [ ]:
file = 'iris.data'
iris = np.genfromtxt(file, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

print(iris.shape)
iris[:10]

(150, 5)


array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa']], dtype=object)

Zadanie 1: Wybierz kolumnę 'species'

In [ ]:
species = iris[:,4]
species[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype=object)

Zadanie 2: Wybierz wszystkie kolumny oprócz 'species'

In [ ]:
iris_values = iris[:,:4].astype(float)
iris_values.shape

(150, 4)

Zadanie 3: Oblicz średnią, medianę i odchylenie standardowe wartości 'sepalwidth'

In [ ]:
sepalwidth = iris[:,1].astype(float)
sepalwidth[:10]

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1])

In [ ]:
srednia = np.mean(sepalwidth)
mediana = np.median(sepalwidth) 
odchylenie = np.std(sepalwidth)
print(srednia, mediana, odchylenie)

3.0540000000000003 3.0 0.4321465800705435


Zadanie 4: Znormalizuj dane w kolumnie 'sepalwidth' wg poniższego wzoru:
        
<img src='images/min max scaler.bmp' width = 300>

Dlaczego to jest ważne można przeczytać np tu: https://medium.com/@urvashilluniya/why-data-normalization-is-necessary-for-machine-learning-models-681b65a05029

normalizacja: 0 - 1,

standaryzacja: srednia 0, std = 1

In [ ]:
sepalwidth_max, sepalwidth_min = sepalwidth.max(), sepalwidth.min()
min_max = sepalwidth_max - sepalwidth_min
sepalwidth_normalized = (sepalwidth - sepalwidth_min)/min_max
sepalwidth_normalized

array([0.625     , 0.41666667, 0.5       , 0.45833333, 0.66666667,
       0.79166667, 0.58333333, 0.58333333, 0.375     , 0.45833333,
       0.70833333, 0.58333333, 0.41666667, 0.41666667, 0.83333333,
       1.        , 0.79166667, 0.625     , 0.75      , 0.75      ,
       0.58333333, 0.70833333, 0.66666667, 0.54166667, 0.58333333,
       0.41666667, 0.58333333, 0.625     , 0.58333333, 0.5       ,
       0.45833333, 0.58333333, 0.875     , 0.91666667, 0.45833333,
       0.5       , 0.625     , 0.45833333, 0.41666667, 0.58333333,
       0.625     , 0.125     , 0.5       , 0.625     , 0.75      ,
       0.41666667, 0.75      , 0.5       , 0.70833333, 0.54166667,
       0.5       , 0.5       , 0.45833333, 0.125     , 0.33333333,
       0.33333333, 0.54166667, 0.16666667, 0.375     , 0.29166667,
       0.        , 0.41666667, 0.08333333, 0.375     , 0.375     ,
       0.45833333, 0.41666667, 0.29166667, 0.08333333, 0.20833333,
       0.5       , 0.33333333, 0.20833333, 0.33333333, 0.375  

Zadanie 5: Oblicz funkcję softmax dla 'sepalwidth'. Poniżej znajduje się opis funkcji ze wzorem:
    
<img src='images/softmax.bmp' width=500>

(e jest stałą matematyczną równą 2.71828). Funkcja exp podnosi e do n-tej potęgi.

sprawdź https://docs.scipy.org/doc/numpy/reference/generated/numpy.exp.html

oraz https://medium.com/data-science-bootcamp/understand-the-softmax-function-in-minutes-f3a59641e86d

<img src='images/softmax.png' width=500>

In [ ]:
np.exp(sepalwidth)/np.sum(np.exp(sepalwidth))

array([0.00944058, 0.005726  , 0.00699375, 0.00632821, 0.01043345,
       0.01408369, 0.00854219, 0.00854219, 0.0051811 , 0.00632821,
       0.01153075, 0.00854219, 0.005726  , 0.005726  , 0.01556488,
       0.02322008, 0.01408369, 0.00944058, 0.01274345, 0.01274345,
       0.00854219, 0.01153075, 0.01043345, 0.00772929, 0.00854219,
       0.005726  , 0.00854219, 0.00944058, 0.00854219, 0.00699375,
       0.00632821, 0.00854219, 0.01720186, 0.01901099, 0.00632821,
       0.00699375, 0.00944058, 0.00632821, 0.005726  , 0.00854219,
       0.00944058, 0.00284345, 0.00699375, 0.00944058, 0.01274345,
       0.005726  , 0.01274345, 0.00699375, 0.01153075, 0.00772929,
       0.00699375, 0.00699375, 0.00632821, 0.00284345, 0.00468805,
       0.00468805, 0.00772929, 0.0031425 , 0.0051811 , 0.00424193,
       0.00210648, 0.005726  , 0.00257286, 0.0051811 , 0.0051811 ,
       0.00632821, 0.005726  , 0.00424193, 0.00257286, 0.003473  ,
       0.00699375, 0.00468805, 0.003473  , 0.00468805, 0.00518

In [ ]:
sum(np.exp(sepalwidth)/np.sum(np.exp(sepalwidth)))

1.0000000000000002

Zadanie 6: Znajdź 5 i 95 percentyl zmiennej sepalwidth

In [ ]:
np.percentile(sepalwidth, q=[5, 95])

array([2.345, 3.8  ])

Zadanie 7: Wstaw w 10 losowych miejsc (te losowe trzeba wylosować ;-p) w tablicy wartość np.nan. Wyklucz możliwość wstawienia losowej wartości do kolumny 'species'

In [ ]:
np.random.seed(100)
x = np.random.randint(iris_values.shape[0], size=10)
y = np.random.randint(iris_values.shape[1], size=10)
iris_values[x, y] = np.nan
iris_values[x, y]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

Zadanie 8: Sprawdź ile jest wartości np.nan w tablicy oraz jaki procent tych wartości stanowią te z kolumny 'sepalwidth'

In [ ]:
iris_values[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
nan_all = np.isnan(iris_values[:,1]).sum()
nan_sepalwidth = np.isnan(iris_values).sum()
nan_all,nan_sepalwidth

(1, 10)

In [ ]:
nan_sepalwidth/nan_all

10.0

Zadanie 9: Wyfiltruj wiersze, które spełniają poniższe warunki: 

- wartość 'petallength' jest większa niż 1.5 

- wartość 'sepallength' jest mniejsza niż 5.0 

Jeśli pojawi się warning, wynika to z wartości nan w tablicy

In [ ]:
iris_values[(iris_values[:, 2] > 1.5) & (iris_values[:, 0] < 5.0)]

C:\Users\oliwia.wojtkowska\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.
C:\Users\oliwia.wojtkowska\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less
  """Entry point for launching an IPython kernel.


array([[4.8, 3.4, 1.6, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

Zadanie 10: Wyfiltruj z tablicy rekordy, które nie mają żadnych wartości nan w wierszach (zrób kopie, tablica z nan'ami bedzie nam potrzebna za chwile)

In [ ]:
print(iris_values.shape)
values_without_nan = np.array([~np.any(np.isnan(row)) for row in iris_values])
iris_values_without_nan = iris_values[values_without_nan]
iris_values_without_nan.shape

(150, 4)


(140, 4)

Zadanie 11: Wstaw zamiast wartości nan średnią z danej cechy dla danego gatunku.

In [ ]:
iris_values_f = iris_values.astype(float)
iris_avg = np.unique(species)
for var in np.arange(iris_values_f.shape[1]):
    for k in iris_avg:
        species_row_indexes = np.where(species==k)
        row_indexes = np.where((species==k)&(np.isnan(iris_values_f[:,var])))
        sr = np.nanmean(iris_values_f[species_row_indexes,var])
        print(f'dla {k} i kolumny {var} srednia = {sr}')
        iris_values_f[row_indexes,var] = sr
iris_values_f

dla b'Iris-setosa' i kolumny 0 srednia = 5.006
dla b'Iris-versicolor' i kolumny 0 srednia = 5.958333333333333
dla b'Iris-virginica' i kolumny 0 srednia = 6.599999999999999
dla b'Iris-setosa' i kolumny 1 srednia = 3.418
dla b'Iris-versicolor' i kolumny 1 srednia = 2.7795918367346943
dla b'Iris-virginica' i kolumny 1 srednia = 2.974
dla b'Iris-setosa' i kolumny 2 srednia = 1.45625
dla b'Iris-versicolor' i kolumny 2 srednia = 4.263265306122449
dla b'Iris-virginica' i kolumny 2 srednia = 5.551020408163265
dla b'Iris-setosa' i kolumny 3 srednia = 0.244
dla b'Iris-versicolor' i kolumny 3 srednia = 1.3270833333333334
dla b'Iris-virginica' i kolumny 3 srednia = 2.0260000000000002


array([[5.1       , 3.5       , 1.4       , 0.2       ],
       [4.9       , 3.        , 1.4       , 0.2       ],
       [4.7       , 3.2       , 1.3       , 0.2       ],
       [4.6       , 3.1       , 1.5       , 0.2       ],
       [5.        , 3.6       , 1.4       , 0.2       ],
       [5.4       , 3.9       , 1.7       , 0.4       ],
       [4.6       , 3.4       , 1.4       , 0.3       ],
       [5.        , 3.4       , 1.5       , 0.2       ],
       [4.4       , 2.9       , 1.45625   , 0.2       ],
       [4.9       , 3.1       , 1.5       , 0.1       ],
       [5.4       , 3.7       , 1.5       , 0.2       ],
       [4.8       , 3.4       , 1.6       , 0.2       ],
       [4.8       , 3.        , 1.4       , 0.1       ],
       [4.3       , 3.        , 1.1       , 0.1       ],
       [5.8       , 4.        , 1.2       , 0.2       ],
       [5.7       , 4.4       , 1.5       , 0.4       ],
       [5.4       , 3.9       , 1.3       , 0.4       ],
       [5.1       , 3.5       ,

Zadanie 12: Sprawdź, czy w tablicy znajdują się jakieś wartości nan

In [ ]:
np.isnan(iris_values).any()

True

Zadanie 13: Podaj ile razy występują poszczególne gatunki (kolumna 'species'). Stwórz słownik z częstością występowania.

In [ ]:
species, amount = np.unique(iris[:,4], return_counts=True)
species_dic = {}
for k,v in zip(species, amount):
    species_dic[k] = v
    
species_dic

{b'Iris-setosa': 50, b'Iris-versicolor': 50, b'Iris-virginica': 50}

Zadanie 14: Dla kolumny 'petallength' ze zmiennych ciągłych stwórz zmienne kategoryczne wg poniższych zasad. Weź pod uwagę braki danych jesli wystepują (nie powinny, jeśli wykonaliśmy poprzednie ćwiczenia).

- wartośc mniejsza od 3 :> 'small'
- 3-5 : 'medium'
- wartośc większa równa 5 : 'large'

In [ ]:
petallength_digitized = np.digitize(iris_values[:, 2], [0, 3, 5])
petallength_digitized

array([1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 3, 3, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], dtype=int64)

In [ ]:
labels = {1: 'small', 2: 'medium', 3: 'large'}
petallength_categorized = [labels[x] for x in petallength_digitized]
random_rows = np.random.randint(iris_values.shape[0],size=10)
for oryginal, row in zip(iris_values[random_rows, 2], random_rows):
    print(oryginal, petallength_categorized[row])

3.5 medium
4.6 medium
5.7 large
5.5 large
3.3 medium
4.7 medium
6.1 large
5.8 large
5.6 large
5.8 large


Zadanie 15: Stwórz nową kolumnę, która będzie iloczynem kolumn 'petallength' i 'petalwidth'

In [ ]:
petal_area = iris_values[:,2]*iris_values[:,3]
petal_area = petal_area[:, np.newaxis]
print(petal_area.shape, iris_values.shape)
new_iris_values = np.hstack([iris_values, petal_area])
new_iris_values[:10]

(150, 1) (150, 4)


array([[5.1 , 3.5 , 1.4 , 0.2 , 0.28],
       [4.9 , 3.  , 1.4 , 0.2 , 0.28],
       [4.7 , 3.2 , 1.3 , 0.2 , 0.26],
       [4.6 , 3.1 , 1.5 , 0.2 , 0.3 ],
       [5.  , 3.6 , 1.4 , 0.2 , 0.28],
       [5.4 , 3.9 , 1.7 , 0.4 , 0.68],
       [4.6 , 3.4 , 1.4 , 0.3 , 0.42],
       [5.  , 3.4 , 1.5 , 0.2 , 0.3 ],
       [4.4 , 2.9 ,  nan, 0.2 ,  nan],
       [4.9 , 3.1 , 1.5 , 0.1 , 0.15]])